In [1]:
# 导入模块
import pandas as pd
from sklearn.preprocessing import MinMaxScaler

In [13]:
data = pd.read_csv("dating.txt")
data

milage     Liters  Consumtime  target
0   40920   8.326976    0.953952       3
1   14488   7.153469    1.673904       2
2   26052   1.441871    0.805124       1
3   75136  13.147394    0.428964       1
4   38344   1.669788    0.134296       1

In [6]:
# 转换数据
transfer = MinMaxScaler(feature_range=(2,3))
data = transfer.fit_transform(data[["milage","Liters","Consumtime","target"]])

print("特征预处理结果：\n", data)

特征预处理结果：
 [[2.43582641 2.58819286 2.53237967 3.        ]
 [2.         2.48794044 3.         2.5       ]
 [2.19067405 2.         2.43571351 2.        ]
 [3.         3.         2.19139157 2.        ]
 [2.3933518  2.01947089 2.         2.        ]]


In [17]:
from sklearn.preprocessing import StandardScaler
import numpy as np

data = pd.read_csv("dating.txt")

transfer = StandardScaler()
data = transfer.fit_transform(data[["milage","Liters","Consumtime","target"]])

print("标准化后的数据：\n", data)
print("标准化前的均值：\n", transfer.mean_)
print("标准化前的方差：\n", transfer.var_)
print("标准化后的均值：\n", np.mean(data, axis=0)) # 按列计算
print("标准化后的方差：\n", np.var(data, axis=0))  # 按列计算

标准化后的数据：
 [[ 0.0947602   0.44990013  0.29573441  1.75      ]
 [-1.20166916  0.18312874  1.67200507  0.5       ]
 [-0.63448132 -1.11527928  0.01123265 -0.75      ]
 [ 1.77297701  1.54571769 -0.70784025 -0.75      ]
 [-0.03158673 -1.06346729 -1.27113187 -0.75      ]]
标准化前的均值：
 [3.8988000e+04 6.3478996e+00 7.9924800e-01 1.6000000e+00]
标准化前的方差：
 [4.15683072e+08 1.93505309e+01 2.73652475e-01 6.40000000e-01]
标准化后的均值：
 [ 2.91433544e-17  8.88178420e-17  4.44089210e-17 -1.33226763e-16]
标准化后的方差：
 [1. 1. 1. 1.]
